# Generated by Django 2.1.4 on 2019-01-13 18:41

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(default='default.png', upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
