# Generated by Django 2.1.4 on 2019-01-14 17:13

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0002_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(upload_to='avatars', verbose_name='Avatar'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
